UTILITIES=$HOME/Utilities
CMDLETS=$UTILITIES/installed/cmdlets
JETBRAIN=$UTILITIES/jetbrains
JAVABIN=$JAVA_HOME/bin
GOBIN="${GOPATH}/bin:${GOROOT}/bin"

export PATH=$JAVABIN:$CMDLETS:$GOBIN:$JETBRAIN:$PATH
